"""initial schema

Revision ID: e21009b1b250
Revises:
Create Date: 2026-06-16 03:01:49.684085

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import airdrome.models
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e21009b1b250"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fuzzy dedup/alias matching relies on trigram similarity; the GIN indexes below need it.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedupgroup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "APPLE_XML",
                "APPLE_MS",
                "SPOTIFY",
                "LASTFM",
                "LISTENBRAINZ",
                "NAVIDROME",
                name="source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "source_id"),
    )
    op.create_table(
        "source_playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "APPLE_XML",
                "APPLE_MS",
                "SPOTIFY",
                "LASTFM",
                "LISTENBRAINZ",
                "NAVIDROME",
                name="source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("folder", sa.Boolean(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "source_id"),
    )
    op.create_table(
        "track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("track_n", sa.Integer(), nullable=True),
        sa.Column("disc_n", sa.Integer(), nullable=True),
        sa.Column("compilation", sa.Boolean(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=False),
        sa.Column("loved", sa.Boolean(), nullable=True),
        sa.Column("album_loved", sa.Boolean(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("album_rating", sa.Integer(), nullable=True),
        sa.Column("title_norm", sa.String(), nullable=False),
        sa.Column("artist_norm", sa.String(), nullable=False),
        sa.Column("album_artist_norm", sa.String(), nullable=False),
        sa.Column("album_norm", sa.String(), nullable=False),
        sa.Column("canon_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["canon_id"], ["track.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title", "artist", "album", "album_artist"),
    )
    op.create_index(
        "ix_track_album_artist_norm_trgm",
        "track",
        ["album_artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.create_index(
        "ix_track_album_norm_trgm",
        "track",
        ["album_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.create_index(
        "ix_track_artist_norm_trgm",
        "track",
        ["artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.create_index(op.f("ix_track_canon_id"), "track", ["canon_id"], unique=False)
    op.create_index(
        "ix_track_title_norm_trgm",
        "track",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_table(
        "dedupgroupmember",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("member_hash", sa.String(), nullable=False),
        sa.Column("canon_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["dedupgroup.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dedupgroupmember_group_id"), "dedupgroupmember", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_dedupgroupmember_member_hash"), "dedupgroupmember", ["member_hash"], unique=False
    )
    op.create_table(
        "playlistlink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column(
            "remote",
            sa.Enum(
                "APPLE_XML",
                "APPLE_MS",
                "SPOTIFY",
                "LASTFM",
                "LISTENBRAINZ",
                "NAVIDROME",
                name="source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("synced_track_ids", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlist_id", "remote"),
        sa.UniqueConstraint("remote", "external_id"),
    )
    op.create_index(op.f("ix_playlistlink_playlist_id"), "playlistlink", ["playlist_id"], unique=False)
    op.create_table(
        "playlistmerge",
        sa.Column(
            "provider",
            sa.Enum(
                "APPLE_XML",
                "APPLE_MS",
                "SPOTIFY",
                "LASTFM",
                "LISTENBRAINZ",
                "NAVIDROME",
                name="source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("surviving_playlist_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["surviving_playlist_id"], ["playlist.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("provider", "source_id"),
    )
    op.create_table(
        "playlisttrack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlisttrack_playlist_id"), "playlisttrack", ["playlist_id"], unique=False)
    op.create_index(op.f("ix_playlisttrack_position"), "playlisttrack", ["position"], unique=False)
    op.create_index(op.f("ix_playlisttrack_track_id"), "playlisttrack", ["track_id"], unique=False)
    op.create_table(
        "source_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "APPLE_XML",
                "APPLE_MS",
                "SPOTIFY",
                "LASTFM",
                "LISTENBRAINZ",
                "NAVIDROME",
                name="source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("compilation", sa.Boolean(), nullable=True),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("disc_number", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("loved", sa.Boolean(), nullable=False),
        sa.Column("album_loved", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("rating_computed", sa.Boolean(), nullable=False),
        sa.Column("album_rating", sa.Integer(), nullable=True),
        sa.Column("album_rating_computed", sa.Boolean(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "source_id"),
    )
    op.create_index(op.f("ix_source_track_track_id"), "source_track", ["track_id"], unique=False)
    op.create_table(
        "trackalias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("artist_norm", sa.String(), nullable=False),
        sa.Column("title_norm", sa.String(), nullable=False),
        sa.Column("album_norm", sa.String(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title", "album", "artist"),
    )
    op.create_index(
        "ix_trackalias_album_norm_trgm",
        "trackalias",
        ["album_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.create_index(
        "ix_trackalias_artist_norm_trgm",
        "trackalias",
        ["artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.create_index(
        "ix_trackalias_title_norm_trgm",
        "trackalias",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_trackalias_track_id"), "trackalias", ["track_id"], unique=False)
    op.create_table(
        "trackfile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_path", airdrome.models.PathType(), nullable=False),
        sa.Column("library_path", airdrome.models.PathType(), nullable=True),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("title_norm", sa.String(), nullable=False),
        sa.Column("artist_norm", sa.String(), nullable=False),
        sa.Column("album_artist_norm", sa.String(), nullable=False),
        sa.Column("album_norm", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_path"),
        sa.UniqueConstraint("source_path"),
    )
    op.create_index(
        "ix_trackfile_album_artist_norm_trgm",
        "trackfile",
        ["album_artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.create_index(
        "ix_trackfile_album_norm_trgm",
        "trackfile",
        ["album_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.create_index(
        "ix_trackfile_artist_norm_trgm",
        "trackfile",
        ["artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.create_index(
        "ix_trackfile_title_norm_trgm",
        "trackfile",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_trackfile_track_id"), "trackfile", ["track_id"], unique=False)
    op.create_table(
        "source_playlist_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["source_playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["source_track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_playlist_track_playlist_id"), "source_playlist_track", ["playlist_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_playlist_track_position"), "source_playlist_track", ["position"], unique=False
    )
    op.create_index(
        op.f("ix_source_playlist_track_track_id"), "source_playlist_track", ["track_id"], unique=False
    )
    op.create_table(
        "trackaliasscrobble",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "APPLE_XML",
                "APPLE_MS",
                "SPOTIFY",
                "LASTFM",
                "LISTENBRAINZ",
                "NAVIDROME",
                name="source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alias_id"], ["trackalias.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_index(op.f("ix_trackaliasscrobble_alias_id"), "trackaliasscrobble", ["alias_id"], unique=False)
    op.create_table(
        "trackplay",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "APPLE_XML",
                "APPLE_MS",
                "SPOTIFY",
                "LASTFM",
                "LISTENBRAINZ",
                "NAVIDROME",
                name="source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_scrobble_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["source_scrobble_id"], ["trackaliasscrobble.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_scrobble_id"),
        sa.UniqueConstraint("track_id", "played_at"),
    )
    op.create_index(op.f("ix_trackplay_track_id"), "trackplay", ["track_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trackplay_track_id"), table_name="trackplay")
    op.drop_table("trackplay")
    op.drop_index(op.f("ix_trackaliasscrobble_alias_id"), table_name="trackaliasscrobble")
    op.drop_table("trackaliasscrobble")
    op.drop_index(op.f("ix_source_playlist_track_track_id"), table_name="source_playlist_track")
    op.drop_index(op.f("ix_source_playlist_track_position"), table_name="source_playlist_track")
    op.drop_index(op.f("ix_source_playlist_track_playlist_id"), table_name="source_playlist_track")
    op.drop_table("source_playlist_track")
    op.drop_index(op.f("ix_trackfile_track_id"), table_name="trackfile")
    op.drop_index(
        "ix_trackfile_title_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_trackfile_artist_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.drop_index(
        "ix_trackfile_album_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.drop_index(
        "ix_trackfile_album_artist_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.drop_table("trackfile")
    op.drop_index(op.f("ix_trackalias_track_id"), table_name="trackalias")
    op.drop_index(
        "ix_trackalias_title_norm_trgm",
        table_name="trackalias",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_trackalias_artist_norm_trgm",
        table_name="trackalias",
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.drop_index(
        "ix_trackalias_album_norm_trgm",
        table_name="trackalias",
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.drop_table("trackalias")
    op.drop_index(op.f("ix_source_track_track_id"), table_name="source_track")
    op.drop_table("source_track")
    op.drop_index(op.f("ix_playlisttrack_track_id"), table_name="playlisttrack")
    op.drop_index(op.f("ix_playlisttrack_position"), table_name="playlisttrack")
    op.drop_index(op.f("ix_playlisttrack_playlist_id"), table_name="playlisttrack")
    op.drop_table("playlisttrack")
    op.drop_table("playlistmerge")
    op.drop_index(op.f("ix_playlistlink_playlist_id"), table_name="playlistlink")
    op.drop_table("playlistlink")
    op.drop_index(op.f("ix_dedupgroupmember_member_hash"), table_name="dedupgroupmember")
    op.drop_index(op.f("ix_dedupgroupmember_group_id"), table_name="dedupgroupmember")
    op.drop_table("dedupgroupmember")
    op.drop_index(
        "ix_track_title_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_track_canon_id"), table_name="track")
    op.drop_index(
        "ix_track_artist_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.drop_index(
        "ix_track_album_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.drop_index(
        "ix_track_album_artist_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.drop_table("track")
    op.drop_table("source_playlist")
    op.drop_table("playlist")
    op.drop_table("dedupgroup")
    # ### end Alembic commands ###
